[toolchain]
package_manager = "npm"

[features]
resolution = true
skip-lint = false

[programs.localnet]
tutor_project = "DC5BMrRcTAQEk2N8B6eYzxDyuCWXjLVqP3MJEg8F2fgu"

[programs.devnet]
tutor_project = "DC5BMrRcTAQEk2N8B6eYzxDyuCWXjLVqP3MJEg8F2fgu"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/deploy-wallet.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 'tests/**/*.ts'"
